### ISSUE TITLE
Modernise README for GTM 2.0

### ISSUE THREAD

**Issue by elisechant** [BKWLD/data-layer-events#1]
Epic package !

**Comment by weotch** [comment]
Ha thanks!  

Can you tell me what's out of date in the README?  You can actually click the edit icon on the README to quickly submit a PR with whatever changes you think should be made.

**Comment by elisechant** [comment]
@weotch cool, i'm happy to submit a PR. Basically the interface in GTM changed *again* - that's mostly it. I'll have to update images in the README and what not. I'll look in to it soon.

**Comment by elisechant** [comment]
(Just popping these here so I can get CDN image urls)

![screen shot 2017-10-23 at 1 57 14 pm](https://user-images.githubusercontent.com/2195815/31870518-2bbde11c-b7fa-11e7-9d88-f5f19d961e92.png)
![screen shot 2017-10-23 at 1 54 13 pm](https://user-images.githubusercontent.com/2195815/31870519-2c0fd5e4-b7fa-11e7-8531-0fcd726c5532.png)

![screen shot 2017-10-23 at 2 00 23 pm](https://user-images.githubusercontent.com/2195815/31870614-8fb5b0e6-b7fa-11e7-83ea-1968ffc7328c.png)

![screen shot 2017-10-23 at 1 59 33 pm](https://user-images.githubusercontent.com/2195815/31870598-76725210-b7fa-11e7-999d-e1e48a12c5f6.png)

![screen shot 2017-10-23 at 1 58 54 pm](https://user-images.githubusercontent.com/2195815/31870578-5aca8244-b7fa-11e7-86d2-29d011643295.png)
